sudo: required

language: java

jdk:
  - oraclejdk8

addons:
  firefox: latest

install: true

script:
  - mvn -U package jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
